application: findmewebapp
version: 1
runtime: php
api_version: 1

handlers:
- url: /css
  static_dir: css
- url: /js
  static_dir: js
- url: /sign
  script: sign.php
- url: /newlist
  script: newlist.php
- url: /makenewlist
  script: makenewlist.php
- url: /.*
  script: guestbook.php
  login: required
  auth_fail_action: redirect